/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Confidence = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null };
export interface IndicatorSummary {
  'rsi' : number,
  'emaLong' : number,
  'macdSignal' : number,
  'emaShort' : number,
  'bollingerLower' : number,
  'macdLine' : number,
  'bollingerMiddle' : number,
  'macdHistogram' : number,
  'bollingerUpper' : number,
}
export interface PortfolioSummary {
  'totalValue' : number,
  'totalCost' : number,
  'totalPnl' : number,
  'totalPnlPercent' : number,
}
export interface Position {
  'id' : string,
  'pnl' : number,
  'currentPrice' : number,
  'entryDate' : bigint,
  'pnlPercent' : number,
  'quantity' : number,
  'entryPrice' : number,
  'exchange' : [] | [string],
  'symbol' : string,
}
export type Signal = { 'Buy' : null } |
  { 'Hold' : null } |
  { 'Sell' : null };
export interface SignalResult {
  'computedAt' : bigint,
  'indicators' : IndicatorSummary,
  'signal' : Signal,
  'confidence' : Confidence,
  'symbol' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface WatchlistItem {
  'lastUpdated' : bigint,
  'currency' : [] | [string],
  'change' : number,
  'exchange' : [] | [string],
  'price' : number,
  'changePercent' : number,
  'symbol' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addPosition' : ActorMethod<
    [string, number, number, bigint, [] | [string]],
    undefined
  >,
  'addToWatchlist' : ActorMethod<[string, [] | [string]], undefined>,
  'getPortfolio' : ActorMethod<[], Array<Position>>,
  'getPortfolioSummary' : ActorMethod<[], PortfolioSummary>,
  'getStockSignal' : ActorMethod<[string], SignalResult>,
  'getWatchlist' : ActorMethod<[], Array<WatchlistItem>>,
  'refreshPrice' : ActorMethod<[string], WatchlistItem>,
  'removeFromWatchlist' : ActorMethod<[string], undefined>,
  'removePosition' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];