/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Position = IDL.Record({
  'id' : IDL.Text,
  'pnl' : IDL.Float64,
  'currentPrice' : IDL.Float64,
  'entryDate' : IDL.Int,
  'pnlPercent' : IDL.Float64,
  'quantity' : IDL.Float64,
  'entryPrice' : IDL.Float64,
  'exchange' : IDL.Opt(IDL.Text),
  'symbol' : IDL.Text,
});
export const PortfolioSummary = IDL.Record({
  'totalValue' : IDL.Float64,
  'totalCost' : IDL.Float64,
  'totalPnl' : IDL.Float64,
  'totalPnlPercent' : IDL.Float64,
});
export const IndicatorSummary = IDL.Record({
  'rsi' : IDL.Float64,
  'emaLong' : IDL.Float64,
  'macdSignal' : IDL.Float64,
  'emaShort' : IDL.Float64,
  'bollingerLower' : IDL.Float64,
  'macdLine' : IDL.Float64,
  'bollingerMiddle' : IDL.Float64,
  'macdHistogram' : IDL.Float64,
  'bollingerUpper' : IDL.Float64,
});
export const Signal = IDL.Variant({
  'Buy' : IDL.Null,
  'Hold' : IDL.Null,
  'Sell' : IDL.Null,
});
export const Confidence = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const SignalResult = IDL.Record({
  'computedAt' : IDL.Int,
  'indicators' : IndicatorSummary,
  'signal' : Signal,
  'confidence' : Confidence,
  'symbol' : IDL.Text,
});
export const WatchlistItem = IDL.Record({
  'lastUpdated' : IDL.Int,
  'currency' : IDL.Opt(IDL.Text),
  'change' : IDL.Float64,
  'exchange' : IDL.Opt(IDL.Text),
  'price' : IDL.Float64,
  'changePercent' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addPosition' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Int, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'addToWatchlist' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'getPortfolio' : IDL.Func([], [IDL.Vec(Position)], []),
  'getPortfolioSummary' : IDL.Func([], [PortfolioSummary], []),
  'getStockSignal' : IDL.Func([IDL.Text], [SignalResult], []),
  'getWatchlist' : IDL.Func([], [IDL.Vec(WatchlistItem)], []),
  'refreshPrice' : IDL.Func([IDL.Text], [WatchlistItem], []),
  'removeFromWatchlist' : IDL.Func([IDL.Text], [], []),
  'removePosition' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Position = IDL.Record({
    'id' : IDL.Text,
    'pnl' : IDL.Float64,
    'currentPrice' : IDL.Float64,
    'entryDate' : IDL.Int,
    'pnlPercent' : IDL.Float64,
    'quantity' : IDL.Float64,
    'entryPrice' : IDL.Float64,
    'exchange' : IDL.Opt(IDL.Text),
    'symbol' : IDL.Text,
  });
  const PortfolioSummary = IDL.Record({
    'totalValue' : IDL.Float64,
    'totalCost' : IDL.Float64,
    'totalPnl' : IDL.Float64,
    'totalPnlPercent' : IDL.Float64,
  });
  const IndicatorSummary = IDL.Record({
    'rsi' : IDL.Float64,
    'emaLong' : IDL.Float64,
    'macdSignal' : IDL.Float64,
    'emaShort' : IDL.Float64,
    'bollingerLower' : IDL.Float64,
    'macdLine' : IDL.Float64,
    'bollingerMiddle' : IDL.Float64,
    'macdHistogram' : IDL.Float64,
    'bollingerUpper' : IDL.Float64,
  });
  const Signal = IDL.Variant({
    'Buy' : IDL.Null,
    'Hold' : IDL.Null,
    'Sell' : IDL.Null,
  });
  const Confidence = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const SignalResult = IDL.Record({
    'computedAt' : IDL.Int,
    'indicators' : IndicatorSummary,
    'signal' : Signal,
    'confidence' : Confidence,
    'symbol' : IDL.Text,
  });
  const WatchlistItem = IDL.Record({
    'lastUpdated' : IDL.Int,
    'currency' : IDL.Opt(IDL.Text),
    'change' : IDL.Float64,
    'exchange' : IDL.Opt(IDL.Text),
    'price' : IDL.Float64,
    'changePercent' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addPosition' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Int, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'addToWatchlist' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'getPortfolio' : IDL.Func([], [IDL.Vec(Position)], []),
    'getPortfolioSummary' : IDL.Func([], [PortfolioSummary], []),
    'getStockSignal' : IDL.Func([IDL.Text], [SignalResult], []),
    'getWatchlist' : IDL.Func([], [IDL.Vec(WatchlistItem)], []),
    'refreshPrice' : IDL.Func([IDL.Text], [WatchlistItem], []),
    'removeFromWatchlist' : IDL.Func([IDL.Text], [], []),
    'removePosition' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };