/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SignalResult {
    computedAt: bigint;
    indicators: IndicatorSummary;
    signal: Signal;
    confidence: Confidence;
    symbol: string;
}
export interface IndicatorSummary {
    rsi: number;
    emaLong: number;
    macdSignal: number;
    emaShort: number;
    bollingerLower: number;
    macdLine: number;
    bollingerMiddle: number;
    macdHistogram: number;
    bollingerUpper: number;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Position {
    id: string;
    pnl: number;
    currentPrice: number;
    entryDate: bigint;
    pnlPercent: number;
    quantity: number;
    entryPrice: number;
    exchange?: string;
    symbol: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface PortfolioSummary {
    totalValue: number;
    totalCost: number;
    totalPnl: number;
    totalPnlPercent: number;
}
export interface WatchlistItem {
    lastUpdated: bigint;
    currency?: string;
    change: number;
    exchange?: string;
    price: number;
    changePercent: number;
    symbol: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export enum Confidence {
    Low = "Low",
    High = "High",
    Medium = "Medium"
}
export enum Signal {
    Buy = "Buy",
    Hold = "Hold",
    Sell = "Sell"
}
export interface backendInterface {
    addPosition(symbol: string, entryPrice: number, quantity: number, entryDate: bigint, exchange: string | null): Promise<void>;
    addToWatchlist(symbol: string, exchange: string | null): Promise<void>;
    getPortfolio(): Promise<Array<Position>>;
    getPortfolioSummary(): Promise<PortfolioSummary>;
    getStockSignal(symbol: string): Promise<SignalResult>;
    getWatchlist(): Promise<Array<WatchlistItem>>;
    refreshPrice(symbol: string): Promise<WatchlistItem>;
    removeFromWatchlist(symbol: string): Promise<void>;
    removePosition(id: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { Confidence as _Confidence, IndicatorSummary as _IndicatorSummary, Position as _Position, Signal as _Signal, SignalResult as _SignalResult, WatchlistItem as _WatchlistItem } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addPosition(arg0: string, arg1: number, arg2: number, arg3: bigint, arg4: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPosition(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPosition(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async addToWatchlist(arg0: string, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWatchlist(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWatchlist(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getPortfolio(): Promise<Array<Position>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolio();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolio();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolioSummary(): Promise<PortfolioSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioSummary();
            return result;
        }
    }
    async getStockSignal(arg0: string): Promise<SignalResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getStockSignal(arg0);
                return from_candid_SignalResult_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStockSignal(arg0);
            return from_candid_SignalResult_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWatchlist(): Promise<Array<WatchlistItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWatchlist();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWatchlist();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async refreshPrice(arg0: string): Promise<WatchlistItem> {
        if (this.processError) {
            try {
                const result = await this.actor.refreshPrice(arg0);
                return from_candid_WatchlistItem_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refreshPrice(arg0);
            return from_candid_WatchlistItem_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFromWatchlist(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWatchlist(arg0);
            return result;
        }
    }
    async removePosition(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePosition(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePosition(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_Confidence_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Confidence): Confidence {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Position_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Position): Position {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_SignalResult_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignalResult): SignalResult {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Signal_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Signal): Signal {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_WatchlistItem_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WatchlistItem): WatchlistItem {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastUpdated: bigint;
    currency: [] | [string];
    change: number;
    exchange: [] | [string];
    price: number;
    changePercent: number;
    symbol: string;
}): {
    lastUpdated: bigint;
    currency?: string;
    change: number;
    exchange?: string;
    price: number;
    changePercent: number;
    symbol: string;
} {
    return {
        lastUpdated: value.lastUpdated,
        currency: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.currency)),
        change: value.change,
        exchange: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.exchange)),
        price: value.price,
        changePercent: value.changePercent,
        symbol: value.symbol
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    pnl: number;
    currentPrice: number;
    entryDate: bigint;
    pnlPercent: number;
    quantity: number;
    entryPrice: number;
    exchange: [] | [string];
    symbol: string;
}): {
    id: string;
    pnl: number;
    currentPrice: number;
    entryDate: bigint;
    pnlPercent: number;
    quantity: number;
    entryPrice: number;
    exchange?: string;
    symbol: string;
} {
    return {
        id: value.id,
        pnl: value.pnl,
        currentPrice: value.currentPrice,
        entryDate: value.entryDate,
        pnlPercent: value.pnlPercent,
        quantity: value.quantity,
        entryPrice: value.entryPrice,
        exchange: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.exchange)),
        symbol: value.symbol
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    computedAt: bigint;
    indicators: _IndicatorSummary;
    signal: _Signal;
    confidence: _Confidence;
    symbol: string;
}): {
    computedAt: bigint;
    indicators: IndicatorSummary;
    signal: Signal;
    confidence: Confidence;
    symbol: string;
} {
    return {
        computedAt: value.computedAt,
        indicators: value.indicators,
        signal: from_candid_Signal_n8(_uploadFile, _downloadFile, value.signal),
        confidence: from_candid_Confidence_n10(_uploadFile, _downloadFile, value.confidence),
        symbol: value.symbol
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
}): Confidence {
    return "Low" in value ? Confidence.Low : "High" in value ? Confidence.High : "Medium" in value ? Confidence.Medium : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Buy: null;
} | {
    Hold: null;
} | {
    Sell: null;
}): Signal {
    return "Buy" in value ? Signal.Buy : "Hold" in value ? Signal.Hold : "Sell" in value ? Signal.Sell : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WatchlistItem>): Array<WatchlistItem> {
    return value.map((x)=>from_candid_WatchlistItem_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Position>): Array<Position> {
    return value.map((x)=>from_candid_Position_n3(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
